### ISSUE TITLE
several issues related to Multisite as well as wp_mail()

### ISSUE THREAD

**Issue by senlin** [afragen/wp-dependency-installer#68]
I received a notice that there was an update for the wp-dependency-installer library available for my plugin Classic Editor Addon.

I updated the script and released version [2.6.4](https://github.com/senlin/classic-editor-addon/tags), upon which the reports about conflicts and other issues started coming in.

- [issue related to multisite installs](https://wordpress.org/support/topic/error-updating-to-2-6-4/#post-15285786)
- [issue related to the `wp_mail()` function](https://github.com/senlin/classic-editor-addon/issues/8)
- [issue related to `SECURE_AUTH_COOKIE` and `LOGGED_IN_COOKIE`](https://github.com/senlin/classic-editor-addon/issues/9)

None of the issues can be directly tracked back to the wp-dependency-installer library, but as soon as the classic editor addon plugin is deactivated, the issues disappear.

Due to the fact that the old library posed a security issue, I have for now released a version of my plugin (3.0.0) where I have replaced the dependency installer library with a simple dependency check/notice. This way the time pressure is off and you can look into this.

Please let me know if you need any other information.

Cheers,
Pieter

**Comment by afragen** [comment]
Hey Peiter! This is very odd.

I'm doing some debugging and I think I see the problem. When I'm creating a nonce the `wp_create_nonce()` isn't yet defined. I load `pluggable.php` and this is creating the issues.

I think the solution is to call the wp-dependency-installer as follows. In my testing this seems to fix the issue.

```php
include_once( __DIR__ . '/vendor/autoload.php' );
add_action('plugins_loaded', function(){
	WP_Dependency_Installer::instance()->run( __DIR__ );
});
```

The issue arises because FluentSMTP defines it's own `wp_mail()`. If `pluggable.php` is already loaded then Fluent's wp_mail never loads. I suspect something similar for any plugin that defines it's own pluggable function.

I'll update the instructions and push out a new wp-dependency-installer, though the current release should have no issues.

**Comment by afragen** [comment]
I'm still looking to see if there's a better way.

**Comment by afragen** [comment]
Not sure there's a better way, but the above should fix everything.

**Comment by afragen** [comment]
BTW, the better solution is one I'm working on for WP 6.0

https://github.com/afragen/plugin-dependency-feature

**Comment by afragen** [comment]
I removed loading `pluggable.php` from update v4.3.2

**Comment by afragen** [comment]
https://github.com/afragen/wp-dependency-installer/issues/68#issuecomment-1020706596 should also fix 
https://github.com/senlin/classic-editor-addon/issues/8
